# Generated by Django 5.0 on 2024-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveBigIntegerField(
                blank=True,
                choices=[(1, "Student"), (2, "Staff"), (3, "Admin"), (4, "Editor")],
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
